### ISSUE TITLE
Contact Management>Add New Contact

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#12]
1. After entering the valid inputs on the fields and clicking on the Add icon, the new contact is added but the toast message is displayed as **Failed to Add Contact** .It should appear as **Contact Added Succesfully**.
2. Contact Category - Need to represent the mandatory fields with an asterisk * symbol.
3. Status - Need to represent the mandatory fields with an asterisk * symbol.
4. Company Name - Need to represent the mandatory fields with an asterisk * symbol.

**Comment by M8Balaji** [comment]
2, 3, 4 -  fields were not mandatory

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Spelling mistake is present in the word **Sucessfully**. Rename the toast message as **Contact Added Successfully**.

**Comment by Gokilavani-m8** [comment]
Rename the FIRST NAME as Client Name

![Screenshot (133)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/4d3ebf40-e880-4e7b-91de-07d5e0bf5a95)

@M8Balaji As you said Bug#2 is not mandatory field. While leaving the Contact Category field as blank, it has been highlighted. Is Bug#2,3,4 is Mandatory field or not

**Comment by M8Balaji** [comment]
4 - field not mandatory, Others I had to make it as required

**Comment by Gokilavani-m8** [comment]
1. Rename the Highlighted message as **Contact Type is Required**

![Screenshot (152)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/05ea8ffe-57fd-4e1d-be12-bf3f6c849514)

2. Rename the Highlighted message as **Client Name can only contain alphabets and spaces**

![Screenshot (163)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/f1357afc-abef-4875-ace4-84c2b6ccd2e5)

3. Email - It's accepting without an extension.com/.in. Need to set the validation properly. While entering invalid email as inputs, it should be highlighted with an alert message. No highlighted message has displayed.
4. Phone Number - It shouldn't accept special characters, alphabet, spaces & numbers less or more than 10 digits as inputs. While entering an invalid input, it should be highlighted with an alert message. No highlighted message has displayed. It shouldn't display as toast message

![Screenshot (164)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/8e164b4a-0f38-45b7-a97d-b30d6af47085)

**Comment by M8Balaji** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Bug#1,2,3 - Not Fixed
Toast Message - Spelling mistake is present in the word **Sucessfully**. Rename the toast message as **Contact Added Successfully**.

**Comment by Gokilavani-m8** [comment]
1. Email - While entering already existing email, it should be highlighted with alert message. No highlighted message has displayed
2. Mobile No - While entering already existing Mobile no, it should be highlighted with alert message. It shouldn't display as toast message

![Screenshot (186)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/eceec219-8243-46e6-aa54-1291b6533697)

3. While adding a new contact and click on the add icon, the toast message appeared as Failed to add contact. It should create a new contact

![Screenshot (185)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/446c40e5-dd04-4654-a682-d4d0d14054f3)

**Comment by M8Balaji** [comment]
1, 2 - Currently not required like that
3 - Add option is removed for super admin, In admin we can add contact

**Comment by Gokilavani-m8** [comment]
Pass
