### ISSUE TITLE
Contact Management>Add Contact

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#14]
1. Company Name - Need to represent the mandatory fields with an asterisk * symbol. All asterisk symbol are represent with red color.
2. Contact Category - Need to represent the mandatory fields with an asterisk * symbol. 
3. Status - Need to represent the mandatory fields with an asterisk * symbol. 
4. Spelling mistake is present in the word **Sucessfully**. Rename the toast message as **Contact Updated Successfully**.
5. Status>Inactive - While clicking on edit icon, the status is shown as Inactive. It should be Active while editing.
6. After entering the valid inputs on the fields and clicking on the Add icon, the new contact is added but the toast message is displayed as **Failed to Add Contact** .It should appear as **Contact Added Succesfully**.
7. Delete Toast message - After clicking on the delete icon, a popup message should display.
8. Need to remove it in mobile number

![Screenshot (74)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/d6d193fe-0f99-44e8-83d0-f870c362bd6a)

**Comment by M8Balaji** [comment]
1 - Not a mandatory field
7 - Create a new issue and please label it as an enhancement

**Comment by Gokilavani-m8** [comment]
1. Client Name - While entering numbers or special characters as inputs, it should be highlighted with alert message. It shouldn't display as toast message

![Screenshot (135)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/b6f466af-6883-414d-81da-828f16a9e093)

2. After entering the valid inputs on the fields and clicking on the Add icon, the new contact is not added and the toast message is displayed as Failed to Add Contact.

**Comment by M8Balaji** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
1. After entering the valid inputs on the fields and clicking on the Add icon, the new contact is not added and the toast message is displayed as Failed to Add Contact - Not fixed

![Screenshot (153)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/3618b3e8-c156-4807-a6b8-2b3794c61ab4)

2. While editing the contact, email & company name is empty. It shouldn't be empty.
3. While editing the contact, the Contact Category is displayed as 3. It should display the proper dropdown list.

![Screenshot (154)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/f53e7f1c-db29-43b7-99a5-5fb4b10aaeec)

4. Search - It's not working

![Screenshot (169)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/d5ef50d0-3dd2-4780-bc2a-f439a8361b82)

5. Rename the highlighted message as **Client Name can only contain alphabets and spaces**

![Screenshot (170)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/6a021aed-0710-4b05-b62e-af34a77b2ad2)

6. Mobile Number - It shouldn't accept special characters, alphabet, spaces & numbers less or more than 10 digits as inputs. While entering an invalid input, it should be highlighted with an alert message. No highlighted message has displayed. It shouldn't display as toast message.
7. Email - It shouldn't accept without an extension.com/.in. Need to set the validation properly. While entering invalid email as inputs, it should be highlighted with an alert message. No highlighted message has displayed.

**Comment by Gokilavani-m8** [comment]
Rename the Highlighted message as **Contact Type is Required**

![Screenshot (171)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/ec33c481-14f6-49b1-b80e-e8f59d9f20e4)

**Comment by M8Balaji** [comment]
2, 3 point - OLd data will have empty data, But Try with new entries

**Comment by Gokilavani-m8** [comment]
1. Search - It's not working
2. After adding a new contact, the toast message has displayed. But in contact list page the new contact is not added. It should display the new contact on the list page.
3. Toast message - Spelling mistake is present in the word Sucessfully. Rename the toast message as **Contact Added Successfully**.

**Comment by M8Balaji** [comment]
1 - fixed
2 - working fine
3 - Prabhu will fix it

**Comment by Gokilavani-m8** [comment]
Pass
