### ISSUE TITLE
Inventory Management>Item>Add New Product

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#2]
1. While adding a new product and clicking on the add icon, it should added and shown on the product list page. But it doesn't added. Need to change it.
2. Delete Toast Message - There is no Popup Message has been found while clicking on delete icon. Need to show it properly.
3. After adding a new product and clicking on the add icon, a toast message should appear as **Item Added Successfully**.
4. Status>Inactive - While clicking on edit icon, the status is shown as Inactive. It should be Active while editing.
5. Spelling mistake is present in the word **Sucessfully**. Rename the toast message for both add and edit page.
6. Product - Need to represent the mandatory fields with an asterisk * symbol.
7. Status - Need to represent the mandatory fields with an asterisk * symbol.
8. Edit - while editing a new stock status, Brand & Quantity has not displayed on the page. Need to show it.

**Comment by M8Balaji** [comment]
2 Point -Create a new issue and label it as Enhancement
1, 3, 5 - Prabhu will fix
7 - not a mandatory field

**Comment by Gokilavani-m8** [comment]
1. While adding a new product, an error message has displayed

![Screenshot (123)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/30a981c5-b813-4861-a160-c031eb5dac5a)

2. Product - Need to represent the mandatory fields with an asterisk * symbol - Not fixed

**Comment by M8Balaji** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
1. While adding a new product, an error message has displayed - Not Fixed

![Screenshot (148)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/24bc20e5-73a4-4157-b06f-48d188436bba)

**Comment by M8Balaji** [comment]
Working Fine

**Comment by Gokilavani-m8** [comment]
Pass

**Comment by Gokilavani-m8** [comment]
Name - While entering already existing name, it should display the proper message

![Screenshot (188)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/1d42b4ac-2680-4c05-b00f-e8eaa8dd5b74)

**Comment by Gokilavani-m8** [comment]
Name - While entering already existing name, it should display the proper message

![Screenshot (188)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/1d42b4ac-2680-4c05-b00f-e8eaa8dd5b74)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
