### ISSUE TITLE
Job Details>Update status

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#30]
While clicking **Spare part pending, Site not ready, Cancelled**, In history it has been shown as unknown.

![685f14c4-8d32-4f26-b180-cdc29c710c82](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/85cc5097-d6bc-4499-bca4-67fa21c1e6a9)

**Comment by M8Naveen** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Need some space in between the words

![1c49b072-3753-4664-a80c-cb3e1b896bc7](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/6594d1a2-3b38-47e2-869f-ac00c9e51967)

**Comment by M8Naveen** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not fixed

![ddd0360c-3a2d-4bd1-822d-e9aa0175350d](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/0843270d-6d83-4b40-a026-a2ab02b6a7e1)

**Comment by Gokilavani-m8** [comment]
Pass
