### ISSUE TITLE
Employee Management>Add New Employee

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/Electo-care#43]
1. Email - It's accepting without an extension.com. Need to set the validation properly.

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not fixed

![Screenshot (208)](https://github.com/Gokilavani-m8/Electo-care/assets/167422482/88d5c03b-94d6-49e8-b358-a4894d8d5789)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Pass
